apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ClusterRole.yaml
  - ./ConfigMap.yaml
  - ./Deployment.yaml
  - ./Ingress.yaml
  - ./Namespace.yaml
  - ./Secret.yaml
  - ./Service.yaml
  - ./ServiceAccount.yaml
