apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager-secrets.yaml
  - ./cloudflared-secrets.yaml
  # - ./dify-secrets.yaml
  - ./external-dns-secrets.yaml
  - ./flux-system-secrets.yaml
  # - ./freshrss-secrets.yaml
  # - ./manyfold-secrets.yaml
  # - ./microrealestate-secrets.yaml
  - ./mongodb-secrets.yaml
  - ./monitoring-secrets.yaml
  - ./n8n-secrets.yaml
  # - ./postgresql-secrets.yaml
  - ./redis-secrets.yaml
  - ./supabase-secrets-flux.yaml
