apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actualbudget-secrets-fluxcd.yaml
  - ./authentik-secrets-fluxcd.yaml
  - ./cert-manager-secrets.yaml
  - ./cloudflared-secrets.yaml
  - ./dify-secrets.yaml
  - ./dota2-wokman-secrets.yaml
  - ./external-dns-secrets.yaml
  - ./flux-system-secrets.yaml
  - ./freshrss-secrets.yaml
  # - ./manyfold-secrets.yaml
  # - ./microrealestate-secrets.yaml
  - ./mlflow-secrets-fluxcd.yaml
  # - ./mongodb-secrets.yaml
  - ./monitoring-secrets.yaml
  - ./n8n-secrets-flux.yaml
  - ./postgresql-secrets.yaml
  - ./redis-secrets.yaml
  - ./supabase-secrets-flux.yaml
