apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cnpg-operator.yaml
  - ingress-nginx.yaml
  - longhorn.yaml
  - metallb.yaml
  - external-dns.yaml
